### ISSUE TITLE
Panel Not Loading

### ISSUE THREAD

**Issue by itsland0n** [Server-pro/ServerProVPSBeta#10]
**Describe the bug**

**To Reproduce**
1. Just open the panel.

**Expected behavior**
I expected the panel to load

**Screenshots**
YouTube Video [here](https://youtu.be/HiBCJsSd_FQ)

**Additional context**
TS 3, Mysql, Nginx, Apache, Minecraft Server

**Comment by sheepa** [comment]
The server does load for me. However if you can include the dev console in chrome, either in the video or in a screenshot. Check the console tab and any red rows in the network tab.

**Comment by itsland0n** [comment]
[Screenshot of dev console](https://prnt.sc/usz0py)

**Comment by Antiquis** [comment]
Would you be able to show the contents of one of the errors (i.e. by clicking the little grey arrow next to one of them)? This'll just give us some more context...

**Comment by itsland0n** [comment]
![image](https://user-images.githubusercontent.com/71981384/95021351-242f1c80-0636-11eb-8c0f-763a5973caf9.png)

**Comment by sheepa** [comment]
Well, its a network issue for sure. If you have access to a VPN or just any other internet connection could you please try that? Did it work in this specific internet connection before?

**Comment by itsland0n** [comment]
It did work on this same internet connection before. I will try using a VPN.

**Comment by itsland0n** [comment]
[Video](https://youtu.be/6qOJ4ItFsQ4)

**Comment by itsland0n** [comment]
I'm screenshotting the dev console now

**Comment by itsland0n** [comment]
Nevermind, there are no errors in there. However, as you can see, only some aspects of the panel are loading.

**Comment by sheepa** [comment]
This seems to be caused by UFW.
