### ISSUE TITLE
Shell on mobile not fullscreen

### ISSUE THREAD

**Issue by cawi** [Server-pro/ServerProVPSBeta#12]
![Image from iOS](https://user-images.githubusercontent.com/773829/95025360-69c90500-0689-11eb-8b43-06b312c68c6d.png)

(Latest iOS)

**Comment by sheepa** [comment]
This seems to be an iOS issue, unfortunately I'm unable to find any fix for it.

**Comment by voigtan** [comment]
It seems to be a safari bug in general.

![Screenshot](https://user-images.githubusercontent.com/765783/95988057-9b2f9680-0e28-11eb-9f7f-660852199471.png)

this was a lazy workaround for mobile: 

![Screenshot](https://user-images.githubusercontent.com/765783/95988116-b0a4c080-0e28-11eb-9a8b-3f90f2b78cf9.png)

**Comment by voigtan** [comment]
the `main #section-main` works in safari desktop and ios if you change the `height: calc(100% -  52px)` to the same height as the navbar `height: calc(100vh -  52px)`

```
main #section-main {
flex: 1;
height: calc(100vh - 52px);
margin-top: 52px;
display: flex;
}
```

demo https://keybase.pub/voigtan/Screen%20Recording%202020-10-14%20at%2020.36.23.mp4

**Comment by sheepa** [comment]
Thanks for the solution @voigtan - this have now been fixed.

**Comment by voigtan** [comment]
Can verify that this works in production also.

**Comment by cawi** [comment]
Great! 👍🏻
