### ISSUE TITLE
Unable to connect through control panel when enabling firewall

### ISSUE THREAD

**Issue by aurgiyalgo** [Server-pro/ServerProVPSBeta#13]
**Describe the bug**
When enabling UFW (Uncomplicated Firewall) the server can only be controlled using ssh, as the Shell and Files tabs on the control panel do not load.

**To Reproduce**
1. Enable the UFW firewall with 'sudo ufw enable'
2. The Shell and Files tabs on the control panel do not load until the firewall is disabled ('sudo ufw disable')

**Expected behavior**
The server should still be accessible.

**Screenshots**
![image](https://user-images.githubusercontent.com/25750692/95028757-95a0b680-069a-11eb-835a-3f649b1ce59d.png)
![image](https://user-images.githubusercontent.com/25750692/95028766-a4876900-069a-11eb-94d2-af1554f52588.png)
![image](https://user-images.githubusercontent.com/25750692/95028783-bf59dd80-069a-11eb-8f31-ecb9c4c73de7.png)
(port 3149 is for ssh, 80 and 443 is for apache, 25565 for a MC server and 22 is the default port for ssh, but the panel doesn't work even with the port open)

**Comment by sheepa** [comment]
Yes, I just noticed this as i investigated with another server that had UFW turned on.

**Comment by Antiquis** [comment]
Quote @sheepa:
"The side-effect was that if you had a tab open with a server that blocked it the number of half-open websocket connections to a specific host is limited in the browser so you would then block out other servers as well
I have added a timeout in order to fix that issue tho"

Resolved.

**Comment by sheepa** [comment]
I think in this specific case it was caused by UFW and not the side-effect. Being able to install UFW without breaking the panel would be nice though..

**Comment by sheepa** [comment]
The good news is that I have found a way so enabling UFW (or any other firewall) will no longer interfere with the web panel. Bad news is that you will all have to reset your VPSes. I'll push the fix in a few days so you have time to backup any data.

**Comment by sheepa** [comment]
This has now been fixed. UFW will no longer interfere with the panel.
