### ISSUE TITLE
GUI for containers

### ISSUE THREAD

**Issue by voigtan** [Server-pro/ServerProVPSBeta#14]
**Is your feature request related to a problem? Please describe.**
I would really like to have my containers that is running "more" visible like the service visibility 

**Describe the solution you'd like**
I would love to have an option to either run it as a community built images hooking in with the "service"-tab on the site.

**Describe alternatives you've considered**
I do not have a solid idea on how the solution would be or look like but there are some things that I have used previous

Portainers templates are quite nice (https://www.portainer.io/) 
an template structure like Traefik.io could maybe also work?

I could possible run my own portainer instance but then I feel like you miss the server.pro GUI 

**Additional context**

![image](https://user-images.githubusercontent.com/765783/95983769-7cc69c80-0e22-11eb-9927-66ef5701f6b1.png)

**Comment by sheepa** [comment]
Thanks for the suggestion, it would be possible to offer the resource bars and service top bar selection (however only with a shell and no files or dashboard) for custom docker containers. I'll consider this and maybe it will be added later. If you want to try it out in the meantime you can create a container with a name that starts with "pro-"
