### ISSUE TITLE
Navigation on running services are not visible on mobile

### ISSUE THREAD

**Issue by voigtan** [Server-pro/ServerProVPSBeta#15]
**Describe the bug**
You cant navigate to a running Service on Mobile

**To Reproduce**
1. Go to service
2. Create a new Service

**Expected behavior**
On Desktop there are tabs listening and you can navigate to any of the service to inspect them.
On Mobile there seems to be no in my view easy way to navigate to this (or quite hidden from a UX perspective). I expect that anything I can do on any device view should be visible on any device type.

**Screenshots**
![96083593-bd272880-0ebd-11eb-890f-c8331de7ade9](https://user-images.githubusercontent.com/765783/96084103-c664c500-0ebe-11eb-9124-8d8829932ee9.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-15 at 08 12 53](https://user-images.githubusercontent.com/765783/96084107-c6fd5b80-0ebe-11eb-9f39-09afc269f7e3.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-15 at 08 12 42](https://user-images.githubusercontent.com/765783/96084112-c8c71f00-0ebe-11eb-97b4-3b79d3e17a8e.png)

**Comment by sheepa** [comment]
If you click the services dropdown it's there.

**Comment by voigtan** [comment]
Does not work on iOS nor my android Samsung s10

**Comment by Antiquis** [comment]
Looks to be a problem with your devices, as I have tried on both iOS and Android devices (specifically an iPhone 11, iPad Pro and an Pixel 3), and have no problems at all.

**Comment by voigtan** [comment]
I cant get it to work on:
1. Samsung S10
2. Iphone or iPad device
3. PC running Chrome
4. Mac running Chrome

So I would really want to question this issue again.

**Comment by sheepa** [comment]
What version of chrome are you running?

**Comment by voigtan** [comment]
@sheepa what versions you want on? PC/Mac/Android?

**Comment by sheepa** [comment]
All please

**Comment by voigtan** [comment]
Its maybe because I only have one VPS/Server at you? I cant see there is any click events bound on the anchor element either.

**Comment by voigtan** [comment]
So far I tested it in 3 browsers on my PC:

PC:

Chrome:
	Version 85.0.4183.121
	Version 86.0.4240.75 (Official Build) (64-bit)

Microsoft Edge
	Version 86.0.622.38 (Official build) (64-bit)



None of them work

**Comment by voigtan** [comment]
Mac:

- Chrome Canary - Version 88.0.4291.0 (Official Build) canary (x86_64)
- Safari Version 14.0 (15610.1.28.1.9, 15610)
- IOS 14.0

**Comment by voigtan** [comment]
So I find it super strange that on 7 browsers in mobile views I cant open the menu at all.

**Comment by sheepa** [comment]
> Its maybe because I only have one VPS/Server at you? I cant see there is any click events bound on the anchor element either.

This is in fact correct. We had an issue earlier with the service dropdown that was caused by an old browser. Can you please try again now. Make sure you get a new version (Ctrl + F5).

**Comment by voigtan** [comment]
Now it works on PC, Android and IOS and Safari Mac and Mac Chrome

**Comment by sheepa** [comment]
Great, thanks for reporting this. It was mistaken for another similar issue but now its properly fixed.
