### ISSUE TITLE
Cant kill services that are broken/non-starting/conflicting

### ISSUE THREAD

**Issue by cawi** [Server-pro/ServerProVPSBeta#16]
Try creating 2 mysql services and then try to delete them. 

Gives this:
https://i.imgur.com/b4uU3ul.png

**Comment by sheepa** [comment]
I'm unable to reproduce this, please give steps on how to reproduce. However some kind of solution for missing config of a service will be looked into.

**Comment by sheepa** [comment]
Service backend handling have been updated in order to avoid broken / missing configs. Service re-creation required, please see discord for more info.
