### ISSUE TITLE
Make the Mysql sevice easier

### ISSUE THREAD

**Issue by SnowmanFTW** [Server-pro/ServerProVPSBeta#17]
**Is your feature request related to a problem? Please describe.**
A nice thing would be to make the whole mysql service easier to manage, ive seen a lot of persons have trouble with it including myself.

**Describe the solution you'd like**
Make the panel for mysql more useful or make using the mysql service altogether more accesible through the command line

**Describe alternatives you've considered**
Another idea would be to make an in depth tutorial about how to use the mysql service but asides from this i dont know

**Additional context**
No

**Comment by Antiquis** [comment]
This is already planned.

There's not much we can do about making the CLI for MySQL more user-friendly, as this is built in to MySQL and not something that we have control over. We are, however, looking in to adding PhpMyAdmin in the future.

With regards to tutorials, this is definitely something we are looking in to.
