### ISSUE TITLE
dashboard error after backup

### ISSUE THREAD

**Issue by Guiller1203** [Server-pro/ServerProVPSBeta#18]
Hello, good morning, I wanted to report a bug in the services section.
When going to the dashboard the service specifications did not appear, this happened after I made a backup.
This error also occurs within the computer interface
Sincerely Guiller12#0684
 
![Screenshot_20201022-200523](https://user-images.githubusercontent.com/73318230/96939392-539db000-14a3-11eb-912a-5a591fee770a.png)
![Screenshot_20201022-200529](https://user-images.githubusercontent.com/73318230/96939394-54cedd00-14a3-11eb-99ef-8dff06673c09.png)
![U
![Screenshot_20201022-200534](https://user-images.githubusercontent.com/73318230/96939396-55677380-14a3-11eb-866a-81ef46a48fed.png)
ploading Screenshot_20201022-200517.png…]()

**Comment by sheepa** [comment]
This is most likely related to the service backend revamp, it was posted in the discord on Tuesday, ill paste it here;

Okay, the services backend handling have been updated, all current running services will no longer load the service dashboard successfully, to fix run "docker rm -f $(docker ps -aq)" in the shell to remove all services (plus any custom docker containers if you got any) and then re-create your service with the same name. Service data should be there.  Note that some configs may be overwritten by service re-creation (nginx for example).  This is still an issue that's being worked on.
