### ISSUE TITLE
Restarting service overwrites default server files

### ISSUE THREAD

**Issue by SnowmanFTW** [Server-pro/ServerProVPSBeta#5]
**Describe the bug**
Every time the minecraft java edition service is restarted it re creates its files

**To Reproduce**
1. Create a minecraft java edition service
2. Edit a default server file (server.prop for example) and save it.
3. Restart the server
4. Go back to server.prop and it is default again

**Expected behavior**
It should save whatever was there and if it already exists dont overwrite the file

**Screenshots**
No need.

**Additional context**
This is happening on minecraft java edition.

**Comment by sheepa** [comment]
Thank you for this report, this have now been fixed. If you have a minecraft service active already you'll need to "re-create" it by simply going in to the dashboard for the service and clicking save & restart.
