### ISSUE TITLE
Restart button seems to glitch the control panel

### ISSUE THREAD

**Issue by aurgiyalgo** [Server-pro/ServerProVPSBeta#7]
**Describe the bug**
When clicking on the "Restart" button, the server appears to stop and start, but after that the dot at the left of the domain which shows the status has been in intermittent yellow since then. The server list says it is online but when accessing the shell it shows a "Server not running.." message and it's been like that for more than 20 minutes. Force stop button is showing instead of Stop and Restart, but it doesn't seem to do anything. 

**To Reproduce**
1. Click the yellow "Restart" button on the control panel
2. Wait for the server to stop and start again (the status changes to red and then to yellow)
3. The control panel shows that the server is loading, but when accessing the shell (using the url, as the panel does not show the shell button until the vps has started) it shows the message "Server not running.."

**Expected behavior**
The VPS should shutdown and start again after using the restart button.

**Screenshots**
![image](https://user-images.githubusercontent.com/25750692/94835941-47758400-040a-11eb-87b4-ebda49985a7b.png)
![image](https://user-images.githubusercontent.com/25750692/94836008-5c521780-040a-11eb-91a8-e301200f0a00.png)
![image](https://user-images.githubusercontent.com/25750692/94836076-70961480-040a-11eb-937d-c6a33e0c04e5.png)

**Comment by sheepa** [comment]
Thanks for reporting this, this have now been fixed!
